apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:alraro/kubernetes-cluster-gitops.git
    path: apps/monitoring/grafana
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true