apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:alraro/kubernetes-cluster-gitops.git
    path: apps/n8n
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true