apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  source:
    repoURL: git@github.com:alraro/Oracle-cloud-services.git
    targetRevision: HEAD
    path: apps/services/platform/cert-manager-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true