---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-sealed-secret
  namespace: default
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBv1zO/MOZP7z/8DMuvZQeng86DZqqUOk8N6onNnhtSQjs9hn3vsE5vV/t3mMROCOVM+q7CL18cbgmEVXdmPEvtsxrXQ8A5sm9G1vNrMpHVyM50D7a7xQKo5clN/gJvGCX5sL/6/VrpCZVNxEYTS1FtC47apIFML0PSh4FqdQnPE6VaArl+WP/ccqRtYbd3ogFGVzRhaPtUH4uNvdx04swFRk1Z/y6qy29TKgB7RXnnfIpNTFNAem0wa3LrkuooGFzZegsfvABNMd6KUSqmNOUpdHO9ZqA//oOiHlBsUEcmWosIR9BubQAoCM9r7yLByNpq7V48ixoSkCD0sr8XdW9cHObfxBNILvUzP/wbxy70BmfhG2McpKrZhMK8sObgqxBBlfZyNMiMcYGjGeswwR4IW0h3p3imdywUovZGStJZGZZpoI2e7Jens1kAyTCuFijWZ5o3Vi9LUGbud/V8skKltsoP1ewA5StzfZgz2Z1vG5vByZpv/mHJO7Zv2QwExW77shioal2u/oAvX4XRz/ezCZ1I/8Tuy0dYzDIOgVG/wVViPTpTj1kqZFAZ516RxPEU831MXdpywDJ2eZ8R7uWdNjVb89EdEJM3ZsvDYPs8ydDkeBMO3ofwc1JP7syXSad6PSvpEVynkQPA+dKYwnEpf3nz9TiHs1U0US7ukHynaPRHm+Vn4u7L/KvCNkO+wfbEqfs8+4OhIGyfUr3fIjJafyGhHxdSQhO5JAumtR+g/10xD9cwXZKD3L08vc8G
    TELEGRAM_CHAT_ID: AgCdWh+TJIHyDSiWdHwX17rbPU9ZsPVKSo2jSJEb+qDs5BCLHyilBt7UBHtMrHOgY+nmsbPG3Rv7Mk35v8arhimlbjhSIKBTjC5BvXP7MoVHOHcF5V36sfPzhZGnv3z+eYrvd3Yr/Ld+8uvcK7JtcBhkqak6ofF78N5OGCmrkI3CZwQDWmz04BzDC/Gb5Rvy2KcGhG/jTitMNsJrUtcOaQ9BU1+GaLGlotXZv8yKSyXhPMpFeu61TpDidVBf2aTl62vtQVHn0wlXov0BizcBzPY1Dp+xE4SUDUNQMSAPZPxGxTODshkmJzH/sN+hTR1mFdIwYiKd9n0tGAEe+6mPjiChigb3FHA8bG3GBccA/9mL0sacqM/9jFX2DBh0SMvGIdV0UtChyYUMxRd6m/Hzk+dPB+NT6U1pm9YdCoNmqn7dA/k/2gHUx3t0woulkWiO2NywT/KEVOd6BpQ+HNGgCZHOzh+d5tMfZb7r4TN04J4d5F7oqyTLteXQ5XvORY7Ya0VJ6qk9/7eI1M5MnZLgVuVJBqvBeGcfm228v3LNHZmIyV6Kg7jczTBSO0wE4fpgFtJ06F17lx/qi0LhHO9bsfvFaZeAoxvhZk7e5HtdVLLGFHmDn/wz5CzTJ7btrMP0CRnTCgsaXRpUaIuL9HX39fUCbxsCSUc1QtRstWkqBHN67W/x+F7ZckZ+TZhZf9/k4+FPL/3hFW9PVGeK
  template:
    metadata:
      name: telegram-sealed-secret
      namespace: default
    type: Opaque
