apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inscripciones-juventud-data
  namespace: inscripciones-juventud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
