---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-sealed-secret
  namespace: inscripciones-juventud
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgAxRI4TFE/L9G8bmQ3MP48UIVERP5A9QH4fwTpHEBpZy8S5bMVdBem0ug6hHwwywUKQCXSaEMjQ3D4yMbf4MMBMW6HDB/esGfn5JnXseuf/hDEGIbPk7sthWHX43FCpiXzwKrt7s9vm/bU7Dh6XfPx88IkXuHL+KyWt7pGZQUcV8TEexgCzNs54l2bN2MUf7gv/9g4pkrV0YvKUBSGQi6Iwi3iiRQbmt+dAeTTSyFd7ZNXbP9VlBR90iBLaSKfnc4vEnUa5uVhx49xY3TxWJO5ijRql58Bt0gCBQxPSmkid+GBwsSwTC8gIBnDZa+Y8skmo6fDFjAIbadBbdlgtAlqJeliixaveH6t9Fk0gB3iShD6e9kpLZl7IDROLYeZzLfrix2EbaVTh6uLrfAOrB9MYu1cLoROg560sfq1Lcxa42HPynYkpdbOOunqpd+6doc9YR/RoCCAGSyIk6nhBX9FDJba8A0SwavN1p6btxpHfJBlCYXCvwmNuKEXS1oB57bq51aEfF0Q61R6Fiw2+OePTW4Ixg5xBCsPb0gTqRhc6sJHGNwANWCWnotS10XF41NzUmQIBHLwKnDwbFBNeym5IqVunSl0fBg5mVcc74GfvpTMHS5J/uFlve6O1S7wh7Yx+6P7HssH7l51BQTsBx++G/LpAcqR1FAqN/rhWeMLEvcvDf0e7Pw+eFHE7JZWjg+w/g7MazrXW4UJZcGPiObwCx1z22Tv5tmEjE/iMgYi8FtXw0pmqeY9JJlcACPwS
    TELEGRAM_CHAT_ID: AgCi1PXXwW1/L7Q5DJ73HgsAkVWsPh31YjbgcTJIGpY41xKqfnUWfsPKveyQtg08amwVoqSWl6PLTbieWTIOKlNIt3WLQfMxu367dXW1aVj2z0V39f15EcJBEmk+5rgizIQc3WSbf/vHt3lxghMvodaWg3045fPnsDFNCt/pGegai89WSKUeMH2fzAFk0BuE5FHvH3FZFpMoT+wjK45eMZSk/nazFU0OrbwNjzWbICQ/RBBlNgARLAq8f1TzHYsK8ra1/I3DzB2lASQ9GeJgJfpMcrq7pfVtqdodJoW92EzwZ37d25sapO3h2h2Tg58W3sbrk1XULOvzgX+h3IJhgXPOHt+EQsZLW9qngBH+dcN2oHYPypHw2vdNdM7GIbvEFURKDu8DH9eyA06MAFsWeoemJ6d24FuUKpzQzXhXgL2AYa2g52ylq4kjOGCg9iEE1eJAFih8cBSpAYInMb80Pu65Frl9wAP8vplw8HsZsAaqmAiA8SoK2Xo+RU4JlFA58Hh9JzXji23u2JPRrd9JPE5MpzX3uSq4l934632/OhgQqhZKifSylqqMAo3XB5bAIYjbjjWbouSMMc/mwQKOwPNEAH9zmteMjtN3EFmvhIjeDnotihFOei9YSRxa9WiSxGuL8AcVfBLmnV2IP+lbtIZsvQcyAFUIUkn2TXWB4KAdOCI29Ge9bYzE3+SWsz7gCPZuRvpO/iVjQ1sQ
  template:
    metadata:
      name: telegram-sealed-secret
      namespace: inscripciones-juventud
    type: Opaque
