---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-sealed-secret
  namespace: inscripciones-juventud
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBtI1xaAe8unFJASBEf87dlzbeaLxwXdKEKrSl6pUXDbqkdwtCiwOQnVttlVtsdSBpx/88tmwbphNUDnnCN6jefjggMm9Y3zOqzC7ZMx0INWDywesDQ6MB55UbZPEc30ArF4qZCUnf4whLxHR4TKU+zLevhHkF9psFOBqocHI+jccv2QxHUESHSUFzdoJQ7sgC2aavFfoSgIvLMqXWt7JBKlj/pmT8SixQkv9ICxr6zpwwrCdkxNxqlty8nXdK5bvQSuIi/LGC4DsF6i+e8XVufsaA9xTDeVwpRLmVRUC2tNVn6l61lFu8CZaDIbY7NRl15XngAYUIF1ImeL04/ObQGgU1i7cHpfP2mE/Eywv6SgW080aDZKMQWy/tJ0W2cqM8mQyKCEorPioz5oYgbvaIinG64y8VUgvOYLKKYyTAFdYVYjipbI7aRwXfoQlEFlX3wvS4YNRxFyNdee2IVjcLaGcLBDlEgBh2oN5idwjEsRZ7dr+qQaKzNlNBMVHxoPdXhlNUMUrJp0G89epr+W3/1dcPgpUGCejU0ARfdSbleIZzB1mH4V7i4VLBofehQ3sRKE6TNoK7lx8UuG6goDx+OozY1dvBqH/44xjp/+QuQfr/zA5ZmDRAC/iK7KBwsnN/lsufxFJiZNPrMfYW5UpmKQGEYK3rQgGr2RmI/RSAOsTjQftejGgi9BUlmer71K61GswQ8sPJeVwklKk3qahhOc01TUlXQk0ju51QVfYgPIQXVQTrDUySiQ/AGi14n
    TELEGRAM_CHAT_ID: AgCiJ5KKHKXQaSQoZKFywpbqwwc/c1ju0Ay/39sQJNA+ryE3peq111BDvbKdcTeLKihgivDu5uTab3HQHgYGncnbAriqCRuiqVZLW4W84D0qibRGlSZuoHRUu+P8jm2DzML0U+HqG7EQp+eIAAY7VTXxSrfsMnaNITrmQuk8bzquT4fOKsI6gP6WceHeYGzf4lH91rXAsqW4039ohsUT1CYiNjhaqXoip7CTtV3Bj3M4qf87dCq9ta7vDYSlnXvADG6vXkqXisi7DyZ5L9Wk3jZ0wW604xcROO+6UQj9e6hl+7BKopVo1w8f1YKUJTxK+AmQU8Tg9DzRAWEynMsvMMCZUih22iKsnUA61WKgMK/hNtrNaGT0SZzGeW6dHdt+kMey9UH4vC41+T+xxByyHd4S32PcrIzK1tsQjz1AjKFwzcxOhuLLpxQBqqc6gOyxCFUJT5jWJZfdHm7LUAaa29k7otE6zro/eudI0KYwpwRix+GwO2qg/0rxkedGMlXI9pxLuh1kjhmMD4InZT5XvxtDScll35LZA2kn3UXG+sA25mycq4q0+cHtPqvrP0N88+HtkDmDEn843xymsTZirHm1QD05fOI+bEyTbuZD+qO0aPeGE9UDdRzlFtaCpkhGdDlz2/3Ki082jmedmmZdY6prz2L/GXnypnF/696DR8VDaQVzGkKi8AheR+Ap6gsF16cxZStC8j2XNAus
  template:
    metadata:
      name: telegram-sealed-secret
      namespace: inscripciones-juventud
    type: Opaque
