# 2. Configuración y Plugins
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_SECURITY_ADMIN_USER: "alfonso"
  GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgA6L9ueoJwuXoJZMvoOZ2GVRdx4ZVUgG4uCwtOF2byJXHexwZNYSyv9Kl47VjjF5kW6qfhLL2M/5AvIfSwydEBjzvckp7371cKVe5iq6NAZaa/C0n3P3NVawjGkmsXjCim19XDqtEPx/JiH2iiA987K8he3i1sVlMzGP3n2dIv4VUj3OlFd/aPtL746SVnNSBFSr3Wr+fWiUPH88ccB08Ryt0o+pIXHg0bpvu1h+wpSBsySp38i4K47qyCN3gxKx2wu3q/1wHf0RiMsr+AybYFXmd8VSPdLxg24bIi0dzRdT6y88kTnsQFHHUpT7/6nV5nI5U5v/l9cMEy3YdCsz3sFYsg6XNwDf9WhsZH8ktM9tzS6DMsbwIFIGzVEuyaZRWefs0fqmAnFVauxhE/cuZ8WPBa/r/FOlv2YSrkorKsBX/YhORqwHQ1rGdaDNXx+ZNBFbvMKhirlqgaKzQTzPBazHzzgccah1cqS9e59XUaz9PH0kA+f/ASDoTksupG2gza9aBIgUuyPtIRmS7EZekI4lnICT9wKaLRVEVFXCmLFqSXXgo13UM7vfJQFLcqzwyLXmRwcBHPMXHhUz8gnSUiRDree/HCVzWjTDJSFuHbhnTpag23iOa1bnvdTc09d9G0YOVKn+Udsq5HTNf7LzugWTmsmvCRpz7yev3IjlYErW/S1QsH3mxtzqgzuOSkgemOWY6IDHA13ffx8Rw==
  template:
    metadata:
      name: grafana-secret
    type: Opaque

---
# 4. Almacenamiento
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
# 5. Despliegue de la Aplicación
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana-oss:10.4.1 # Versión fijada
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: grafana-config
        - secretRef:
            name: grafana-secret
        volumeMounts:
        - name: grafana-storage
          mountPath: "/var/lib/grafana"
        ports:
        - containerPort: 3000
---
# 6. Servicio Interno (ClusterIP, NO NodePort)
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: ClusterIP 
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
---
# 7. Regla de Enrutamiento para Tailscale
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.tudominio.com`)
    kind: Rule
    services:
    - name: grafana-service
      port: 3000