# 2. Configuración y Plugins
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  example_key: example_value
---
# 4. Almacenamiento
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
# 5. Despliegue de la Aplicación
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana-oss:10.4.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: grafana-config
        volumeMounts:
        - name: grafana-storage
          mountPath: "/var/lib/grafana"
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage
---
# 6. Servicio Interno (ClusterIP, NO NodePort)
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: ClusterIP 
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.alfonsoramos.dev`)
    kind: Rule
    services:
    - name: grafana-service
      port: 3000
  tls:
    secretName: grafana-tls-cert