---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB3x/SKz5m1igUD/g+bpN/h3hnYiUQQ3Aa4SARbAshYFy7bRBAq7h8kyBadtTuKOIrc9JlRZ68/AJmCSGmrtUOJaiXkkYcHchs6jeUfv7vXvr416om55czVT2dMRwvVBbA6186yXpTNnr3w+4WiOTE7a3W4nIDfD8IAIzTRoGL+3wAlgezvTjcUUOggVgB80BFdfsnWFfcraizqB5hftJvPMk+jc3YXuEefdZCeLjXEALiDI6cWTkl7G9HqiNHotall3VOr0LjzmHQ6qOWnqtVFtos+Sgs8R1Xq+XjCjuLL90Tvg+EXOaomajkz/FlmpQ8OG8zfIWVEB6TqV8wpJ+UKc8G9f0CYlZyVbtTxsCZP6UkxNbYMbJX1QyfbakxXXGFKhfZcX9Nn2V34jy7GcET5B27doJTHmI+erMYpB+Efo5j1WuY0JDngVBaBCaV/pfQgCPElf1AUZ5sfO/crxpJRx78Mh9HCzyrXgJ7Psg0lDd4YLfeQoYXCVI8EyFs5N0v718mU9u9rr4Ldk9VJRCZi/OjdBqlh+i1wgAq8YeYH999ShNt9agKJ6FIqjHackykTziTvpCL9Aw9FXBRIJTiIZ9cFhJHCU1bES3oollSu6E0roTYr5W4SmAx+6zqKGWUBEOZ4M+3tqyO0E16COJB3m5lDEIk5Z5ZKTw/solrSaoLc8tFfZrQJFIO/AHzd2NFYU6bTTKxaTtvnh3JQiebYx1E2+FD+ojcMxXqgu1bu8rWJgpC7ni62KVXFLvT6lVNKUDElLw==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
