---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-default-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCepEYVa49W288dv60DhQg47rYq9viLQJT2CMlq/gcYH4b0e/FyndgXR9T66Jti8kNfgvcCKr4qVq/cLZQyXEcD8ibfDPNmuJbzTykg5PKq6PuxtjsIvdMlAKbeewwmUlEORWT6wC3pjD+P3atcHGklqcIL3idFrD4NR0tvzOLC/gP+JloKTlSgJCvr+4YySD7VmYfBDChu+R2iHtMqo+5f0wvLDsyHv6TdBKtWVZcJxUZSGzPgBG6mqK5hsevSdktUksHukLiIknyoQsLXZj6j/gWnS40XJZK00Co6xqJ/OjABByII2qME56dqInPElHKNsQeSp+MYLwqF5XR3eqEhLvBOsx/0iYmtQOvgIlsbhtbijvDJ8ypkBT2Yle99VSj+xe4sio2lXDFnJg3FF7whocNoydmmIKO40AjTAxOIHhKPe6UBqawnhV03tOKi/kEN0I6V4YyJ/eKoZQGfSyz7MYWuUejVeZUHkkLVBZnM9PxE+QN+sladF9PKDxTlBULxLmKhFgoPs61BLgrYd6IWcSyhPnrPJLhwQQqBLlfpd/TCXvlpypsEAJ3a9v/2YgRKzCN2+gJl4q7ClffsfIhQ0hJHUOjajFR+ybygNQgPoGM8nth6I0FcTJm/iU5gu80bghH8ms0831dQo6BSbAa//T3axCcyGTBlOQLQofX8WMjA1TNGf2k0xMDLgCb+iTL+AHB9b996yQRkWQ==
    admin-user: AgBABDL8HlRgSL9ioBAjblingliaAdAYonoOCJuRCA4ChAYX9wwl0jeyVakbj2nopc3fD1KLIC5zkDPxL0ORoBFUScU90zNdAdeWgqEfrpIKDDcvkpphOQ8nTolQg/UGNv8MsgznAwFjL3fB30cBpAkUCBkfr8RJA18E2aqMwoUkg8cSitwT8Us5gvIdxfqmfNdQiHlnNxvBqGQJCGkdm78suHTRXFgNiBUz7RN3e2RUGkqcKSXvxxOMIuK4tXHSnd2/7IQYJYeZBuvVsfVx1kl4jImxYieop8xYc2rD3VDLtr2yO2RNsd3fHBGEcBBNmCbDWES057xPsH798sbu3CIuNh8XhLwdBU0J6ceY53Cc9as6NOdySpO4ojHiSX5mYM7G/WD1q9AhG7hv/Qv+O1WgmyJclzrWNluu85dlC2q4x7jDu8c6BXU/YNcuukGWqPr5yTSnTz5F8lZh2dxHt89Z8bXNlR+Fp9FtjE0xdTSs66IPSp91cgoFQS4SyiiI0P0NQtZf92YP04VvvpcMCXCnjlmbSM0kYZN/cAbbcZLGvm3TO3EXGa6FDaMHH/YTAr2aoCMmgEx9jteUoDhDqVtzNqO92m/igwB3/aSNN/Xj68glNy8aZuZ0pSXp2iIxrqNgvSe/VgHXbvmoNLi3+DuJ7nxqzh3jMR4fKEgYystKQQRQ5AmXLHH1Z21hVFY4FNEfO3iqnA==
  template:
    metadata:
      name: grafana-default-admin-credentials
      namespace: monitoring
    type: Opaque
