---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-default-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCNsdC9ktUPmZwYK5KF2CO46vQY9HAaL+1Bms12CEUk7oQU6UQ13ukByoJW/wN08Jea1wSp91Ws3KevyBRNKTXhOCvRZREZwilIz/28b1UaYUE7WT+P7b+V5mXq860h1BIjPWXB1tVbDuEhf5Va0VL2FoZRHnZwKdtjTHukhRNaX7AfShylFjiksgPXJdIxvc2qOi0FASNU8kVKgoUQYdIFk6Rv14YJiVI5KNS5g96N2MC0dpHDey/IxPVple8G/2Vabyt8KXA98zux3UNIYNHq9fi+kVqgbbn/oDve9ZY5heOvp8k2qkq2kFJOLjdjQc66Ije1W8fnbEALyU/SCZGX8fauCAHPCEe0bw2DXt02RJTuMkexRXWjU+naSaPGTa8S2rgQJkgqN+md59z1eGPEc96yqQtcTyfhqzkb8ywr+o5VqOP/yjFusdyU/j8nY6Q6JEo1XbSgVLTYuYYgBtneMh8FaB6BSCp6UopvUbLr05J4MEs1lCqA5unp6JxGPdVQeNV2RgKIHlaPVu4+kKfWi7u6ZLUBTu2xpjEa0VrVBvSRWnv2xgBoR4gOadSBmGpdrhJ0dsjp4zCuq9HQ+plbNovdK4dFyzsUq9c6EPxWgIKmPHgNnZCN/mSDISkSS8387yUF/Yw81zKEXoEwEYzEizuJKugMHbmsta6oOXMvPA7dfLNzm/tVuPR5cf7802U88zGOYjoaT3k+kw==
    admin-user: AgAS1/9XmYDRKIm7g0VUhojR6lx5NPgJz//HRsfJdtb1T684xiLSc+Z+A7ZdrZYcve1JUVGw58/m2dbHd6qlZO764Y5G+gD8McN4A53sMABYPwOiXZDUPX31ibgWtLWCHOmGfBciSokiVxm8epsCFc2Se5CHRJjAW9m7vfaKHjCK6zrlWLnV2OUsqOx7MUovnvArKLY/nzJrCC0pOiEfYGW2EfK2RyGhf5IMkith3eOAywLxgfjneT4CkuFMjEYx9F9V46ikGP8T0NJIqu51jKtcUodG2FuT4i5oc3Jc3N2LawYwGIhdOKZOFB7Y7i84TLtJ1ldAGlG8zfLJBeJvoRV6Sj2ke+sgb62nvrggm1OaIxlzV4VN4wRVyLyVVfOFTAU0X7itE+Jzk8hgIEQ+VyzSj3zM1MlSxRo+oxiWQsSzj6CDJr1KzJJEACy9NU8VUHzi9qJNAZKvPsUDp4Jr7bb/HS4K2SIDbLBRccnmeamMp1HOKwbAMluyxP07Y/Owh0+Lfun4F3vWhprn45SC76DL5EMe0zXiuQWWOX4Ea4y1xVsKPEz0YpqsroGBXINoq0+cNbVNNJ9f5LLdd3VbO25+Fp+4oG95BhJpPjonUqlJ6FXO0AglgWGy7djYRB8PQNGsLogbyFPgyik2mUUnHSX795ioreTCoeowRr8xIKAQN4XJFFegIC0wpozOUyz3XahcYg2r4Q==
  template:
    metadata:
      name: grafana-default-admin-credentials
      namespace: monitoring
    type: Opaque
