---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-default-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCjHvZSf9Ru8FGeQC9KSSofGpNSwMtJ9UgBXM2RjwTEVRCefEjtYkYzb6xLAoHL3j4f1dUFu70rLcj2YFXkXgZKw5yYgaji4XM0bwtt8NWsD4lTK4u+VZj5qvX8WKayVTd4ZWn+qYxBjKBDr2oyfONR0alI8ktUv+hhmXCPXys7nHtQWYkR9e4BBH/0IysW2durD9AX78aksWHV1jL3Pj7o9GTbv5/IXxBDj/JUbRqr0CiwnfCN5Abt2DffHNblTxbtEJpEMBrYV7CtDmraXFC5Aoc9xezoM9CQYz1vdubSsid8Y1G2maD3wWTKXOZlUe34IY+WDcOD+glGQ6xiUw65/Sojah6NsWPI/0+kiVyblDgnorshXgpP5tnPsUs/ybpdtVGUduztd1cxhE4F/yo4boFth9uUeYiyuVJK6CmwrJLAPdMC7a1k4gASv9nqzWmAMnzroLO3Ap/Pvslmfy6k11hu68pR9S8v5bqnDz57AFNXS3omlYm9lKlHOw4DOJ5/Bat0xvDH+tkA9rVGeKwl0a+IwNXhNuuSfjP3spgQmHYliqOTshlTuYy8XVoWz8bMeE+pR5VUJ+JXBDmFG035ZvL14LVAOVdtq7b7AuDQ0vSAkCmYuLoECDioDR8iif7rCc2sSuNNB91Lodl+iggxUMWYu0rS072ncxWK8k2MtDcEJnUSMpC13XocCQZOHGMAv/rTBka8qalwwg==
    admin-user: AgBSYHxJm1R9AUi2CVUlT+36TUsI88K50vX3wxxMkLOB+lDlcLG6WGEFJzT91I+WhLPETjqR7lgXo0MwVOIWafa0vBiIkDY6p8uLDL1kCIxj6YuEOUwvEAqudtR1gGTydnb9y4NtOqoyLDGcNkX7OC3Zgp4/dReHMI+lYFhM1hhJhjeBltOgLrj+Y4+wHmM646o5Mbww6T3iJa4nzlgbS+qAhGYOYR417UAH4BsC9AnuoK0R6MOucyC4OKUKZm4KlMhh55pS0Lo/5LubrTKkr+AFNkKxgta1IociP6TaM0pXq//O7mnK6jm1w+6vmhevTRAyj+4c1FW9pvEdXUT6VxeJZVUzgFA3jMOhoMiLmQgFsQmvgom5FP/MOE5znYRcBadFmP++GrmRS/uJxR4JNMkUBZ3sfa4FmhVBMjxrJIIdwwA1LlVwt3NNFKaDq4RQLAI+51jiAhPSIoNQUqxYNhVAoiYLEaSeechO3MAAvTDC+4g0dVdNMv6aksBDen21WuwRu/onbSj31m2jb5PcIkVZ/EbeQfux6+Jw2UQXOW4Ukxq3eK7mHn7AFmhSA3vRWWD9PaenJqIWn7rTkkVlSFCvHSLqs6kGTZyOr85LJ7ayALH5xyqAOKGKmRjwZ/ik34KK/QZFp/GRHjTE8R7JQINfVER/iIIWF7XqWBkNbYetEkP1CCrnTBf+hv7Vw7lZNnX2Qh62gA==
  template:
    metadata:
      name: grafana-default-admin-credentials
      namespace: monitoring
    type: Opaque
