apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  nodeSelector:
    kubernetes.io/hostname: software-minecraft-server-fauna
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  TYPE: "NEOFORGE"
  NEOFORGE_VERSION: "21.1.211"
  VERSION: "1.21.1"
  MEMORY: "12288M"
  ALLOW_FLIGHT: "TRUE"
  MAX_TICK_TIME: "-1"
  DIFFICULTY: "hard"
  MODE: "survival"
  ONLINE_MODE: "FALSE"
  ENABLE_COMMAND_BLOCK: "TRUE"
  SPAWN_PROTECTION: "0"
  PVP: "TRUE"
  SERVER_NAME: "Servidor de Software"
  LEVEL_TYPE: "minecraft:large_biomes"
  MOTD: "    §a§l¡Server del Software! §f- §c[NeoForge 1.21.1]§r\n          §6§kaaaa§6 » §e§lFauna & Orchestra §6« §6§kaaaa"
  PACKWIZ_URL: "https://raw.githubusercontent.com/alraro/Server-Minecraft-Software/refs/heads/develop/my-packwiz/pack.toml"

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: software-minecraft-server-fauna
      containers:
        - name: minecraft
          image: alraro/software-modpack-fauna:2.0.0
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: minecraft-config
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "10Gi"
              cpu: "2000m"
            limits:
              memory: "13Gi"
              cpu: "3500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data