---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-secrets
  namespace: default
spec:
  encryptedData:
    RCON_PASSWORD: AgAG91LeQjbjSw/njpMWc9IEl1smEDKbCwJb/8W8jos64BSpuN1md9jdHpbKUUUdotYFgoTby2Hckz5JQeiq6u7I0C7SjaPof6Xbh7u6XlLQ8OPLkTnk+hmgy6g+KOPmw22EvKEADLX8mk+4d5gK2epdTVbCdOaJnsiF0XAP54fOc+RzequRBIOlnmbQ8P1EQB8+T8jAYBURms3fsTYYlFg9Pkg32JQm+x3XtJPjVMC3uQkxcC+2wRDkWblVIcWp3Qu1dj2YTYLK8cu+qgSyaU6wHwM06y7eTSgs12tWjC8s+inLu92B5ZeFQP8Rkhs791PFoJ/+SpxxOEmDGJkK2pfER2j499qwOeLE5I7YRqESp402kEa/gUpks0EK4D8AadzU7FjU1GNVkqOaNW+7MWjEKV/UzSG2OUE5gQKPbT+P0ZwU2csVHU6RZchd5QiKJHtmRM6AdajU4DbPRMk/wikrc4bilbJlZ9EaNoxcvuP9bg/slxPPzlhBCEtNYBfNOq4W0ECFA2wOeRTYRf1toIVSZT0lllU9X664Xend+jG21QV+/xjUfx77wiNhcaBNOYIxHlZlSM+39RQ8LbZzqDbdyQY+qZJq5i3W/jARkqScIe8+G1zIRKH71czP1+8IwjtUvlfIk3KCuB49jNC4P2VsvPzpZgSlukv4ISvH/imG/ZKXEwyLMoU2fkNbVbTyftB+6eUTPi/vuZdg4bbQFB5v
  template:
    metadata:
      name: minecraft-secrets
      namespace: default
