apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: software-minecraft-server-fauna
      containers:
        - name: minecraft
          image: alraro/software-modpack-fauna:2.0.0
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: minecraft-config
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "10Gi"
              cpu: "2000m"
            limits:
              memory: "13Gi"
              cpu: "3500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data