apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  accessModes:
    - ReadWriteOnce
  nodeSelector:
    kubernetes.io/hostname: software-minecraft-server-fauna
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
